version: '3'

services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - "./config:/config"
      - "./PersistedData/MetaTrader5App:/config/.wine/drive_c/Program Files/MetaTrader 5"
    ports:
      - 3000:3000
    env_file:
      - .env
  
